"""Initial migration

Revision ID: 1cea3bf56a42
Revises: 
Create Date: 2025-09-20 13:18:53.218726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cea3bf56a42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_value', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_jobs_enabled', 'scheduled_jobs', ['enabled'], unique=False)
    op.create_index('idx_scheduled_jobs_status', 'scheduled_jobs', ['status'], unique=False)
    op.create_index('idx_scheduled_jobs_workflow', 'scheduled_jobs', ['workflow_name'], unique=False)
    op.create_table('job_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('items_successful', sa.Integer(), nullable=True),
    sa.Column('items_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scheduled_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_index('idx_job_executions_job', 'job_executions', ['job_id'], unique=False)
    op.create_index('idx_job_executions_started', 'job_executions', ['started_at'], unique=False)
    op.create_index('idx_job_executions_status', 'job_executions', ['status'], unique=False)
    op.create_index('idx_job_executions_workflow', 'job_executions', ['workflow_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_executions_workflow', table_name='job_executions')
    op.drop_index('idx_job_executions_status', table_name='job_executions')
    op.drop_index('idx_job_executions_started', table_name='job_executions')
    op.drop_index('idx_job_executions_job', table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index('idx_scheduled_jobs_workflow', table_name='scheduled_jobs')
    op.drop_index('idx_scheduled_jobs_status', table_name='scheduled_jobs')
    op.drop_index('idx_scheduled_jobs_enabled', table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    # ### end Alembic commands ###
