"""Add Twitter and Reddit source types

Revision ID: 9520bfa45c20
Revises: 1cea3bf56a42
Create Date: 2025-09-20 13:42:06.196827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9520bfa45c20'
down_revision = '1cea3bf56a42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
